name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # 또는 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build && touch out/.nojekyll
        env:
          NODE_ENV: production

      - name: Fix path issues
        run: |
          cd out
          find . -name "*.html" -exec sed -i 's|href="/_next/|href="./next/|g' {} \;
          find . -name "*.html" -exec sed -i 's|src="/_next/|src="./next/|g' {} \;
          cp -r _next next
          cd ..

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true